# Generated by Django 5.0.3 on 2025-05-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
