# Generated by Django 5.0.3 on 2025-05-31 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
