# Generated by Django 5.0.3 on 2025-05-31 01:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_image_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='clip_embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
    ]
